### PR TITLE
MLPAB-797 - detect changes in lang and web

### PR DESCRIPTION
**Pull request by andrewpearce-digital**
# Purpose

Ensure that changes to /web and /lang trigger a build of the docker image and a deployment of the same.

Fixes MLPAB-797

## Approach

- add new paths to git diff command

## Checklist

* [ ] I have performed a self-review of my own code

### CODE REVIEW

**Comment by andrewpearce-digital** [comment]
no changes correctly triggered
image

**Comment by andrewpearce-digital** [comment]
change detected in app
image

**Comment by andrewpearce-digital** [comment]
change detected in lang
image

**Comment by andrewpearce-digital** [comment]
change detected in web
image

**Review by hawx — APPROVED** [review]

**Pull request merged**
